site_name: MtnMe.sh
site_author: MtnMe.sh
site_description: "Mountain Mesh: Serving Meshtastic to the Appalachian Mountains (North GA)"
site_url: https://mtnme.sh/
repo_url: https://github.com/MtnMesh/mtnmesh.github.io
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Devices: devices.md
  - Resources: resources.md
  - Neighbors: neighbors.md

plugins:
  - search
  - social
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - git-committers:
      repository: MtnMesh/mtnmesh.github.io
      branch: main

markdown_extensions:
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  favicon: static/favicon.png
  icon:
    logo: fontawesome/solid/mountain
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.action.view
    - content.action.edit

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/4WN32RHGSs
    - icon: fontawesome/brands/github 
      link: https://github.com/mtnmesh
