site_name: MtnMe.sh
site_author: MtnMe.sh
site_description: "Mountain Mesh: Serving Meshtastic to the Appalachian Mountains (North GA / East TN)"
copyright: © Creative Commons Attribution-ShareAlike 4.0 International License
site_url: https://mtnme.sh/
repo_url: https://github.com/MtnMesh/mtnmesh.github.io
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - About: about.md
  - Guides:
    - MediumFast Migration: mediumfast.md
    - Config: config.md
    - Filters: guides/filters.md
    - 'Flashing the MeshToad or MeshTadpole': guides/flash-meshtoad-meshtadpole.md
    - Ringtones: guides/ringtones.md
  - Devices:
    - MeshToad: devices/MeshToad.md
    - RAKWireless Solar: builds/rak_solar.md
  - Resources: resources.md
  - Neighbors: neighbors.md

plugins:
  - search
  - social:
      cards_layout: default
      cards_layout_options:
        background_color: "#2C2D3C"
        color: "#67EA94"
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
  - git-committers:
      repository: MtnMesh/mtnmesh.github.io
      branch: main

markdown_extensions:
  - toc
  - attr_list
  - tables
  - def_list
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  favicon: static/favicon.svg
  logo: static/logo-no_text.svg
  icon:
    logo: fontawesome/solid/mountain
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.view
    - content.action.edit
  custom_dir: overrides
  palette:
    # The custom Meshtastic theme uses `slate` as a base
    scheme: slate

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/4WN32RHGSs
    - icon: fontawesome/brands/github
      link: https://github.com/mtnmesh

extra_css:
  # Custom styles for Meshtastic theme
  - static/styles/extra.css
