site_name: MtnMe.sh
site_author: MtnMe.sh
site_description: "Mountain Mesh: Serving Meshtastic to the Appalachian Mountains (North GA)"
site_url: https://MtnMe.sh/
repo_url: https://github.com/MtnMesh/mtnmesh.github.io
nav:
  - Home: index.md
  - Devices: devices.md
  - Resources: resources.md
  - Neighbors: neighbors.md

plugins:
  - search
  - social

theme:
  name: material
  favicon: static/favicon.png
  icon:
    logo: fontawesome/solid/mountain

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/4WN32RHGSs
    - icon: fontawesome/brands/github 
      link: https://github.com/mtnmesh
